# conf/config_efficientdet.yaml
train:
  class: pid_train.datasets.effdet_tiled_dataset.EffdetTiledDataset
  image_dir: "/home/rune/dev/pid/assets/image/all/images"
  annotation_file: "/home/rune/dev/pid/assets/strategy_comparison/iterative/annotations/train.json"
val:
  class: pid_train.datasets.effdet_tiled_dataset.EffdetTiledDataset
  image_dir: "/home/rune/dev/pid/assets/image/all/images"
  annotation_file: "/home/rune/dev/pid/assets/strategy_comparison/iterative/annotations/val.json"
tile_size: 512
overlap: 0.25