# conf/config_efficientdet.yaml
train:
  class: pid_train.datasets.effdet_tiled_dataset.EffdetTiledDataset
  image_dir: "${oc.env:PROJECT_ROOT}/assets/image/all/images"
  annotation_file: "${oc.env:PROJECT_ROOT}/assets/strategy_comparison/iterative/annotations/train.json"
val:
  class: pid_train.datasets.effdet_tiled_dataset.EffdetTiledDataset
  image_dir: "${oc.env:PROJECT_ROOT}/assets/image/all/images"
  annotation_file: "${oc.env:PROJECT_ROOT}/assets/strategy_comparison/iterative/annotations/val.json"
tile_size: 512
overlap: 0.25
debug_image_count: null