_target_: pid_train.datasets.coco_style_dataset.CocoStyleDataset

train:
  image_dir: "/home/rune/dev/pid/assets/image/all/images/"
  annotation_file: "/home/rune/dev/pid/assets/strategy_comparison/hybrid/annotations/train.json"
val:
  image_dir: "/home/rune/dev/pid/assets/image/all/images"
  annotation_file: "/home/rune/dev/pid/assets/strategy_comparison/hybrid/annotations/val.json"
