train:
  class: pid_train.datasets.coco_style_dataset.CocoStyleDataset # _target_을 class로 변경
  image_dir: "/home/rune/dev/pid/assets/image/all/images"
  annotation_file: "/home/rune/dev/pid/assets/strategy_comparison/iterative/annotations/train.json"

val:
  class: pid_train.datasets.coco_style_dataset.CocoStyleDataset # _target_을 class로 변경
  image_dir: "/home/rune/dev/pid/assets/image/all/images"
  annotation_file: "/home/rune/dev/pid/assets/strategy_comparison/iterative/annotations/val.json"
