model:
  _target_: pid_train.models.architecture.ObjectDetector
  model:
    _target_: pid_train.models.factory.create_efficientdet
    num_classes: 146
    pretrained: true
    model_name: "tf_efficientdet_d0"
    gradient_checkpointing: true
  val_requires_targets: true # 검증 시 targets 필요 여부 플래그