model:
  _target_: pid_train.models.architecture.ObjectDetector
  model:
    _target_: pid_train.models.factory.create_faster_rcnn
    num_classes: 146
    pretrained: true
    gradient_checkpointing: true # 그래디언트 체크포인팅 활성화
