_target_: pid_train.models.factory.create_model
framework: torchvision
model_name: "fasterrcnn_resnet50_fpn" # fasterrcnn_mobilenet_v3_large_fpn, fasterrcnn_resnet50_fpn
num_classes: ${num_classes}
pretrained: true
gradient_checkpointing: true