_target_: pid_train.models.factory.create_model
framework: torchvision
model_name: "ssdlite320_mobilenet_v3_large" # "ssd300_vgg16"
num_classes: ${num_classes}
pretrained: true
gradient_checkpointing: true