model:
_target_: ocr.models.architecture.ObjectDetector
model:
  _target_: ocr.models.factory.create_yolo
  num_classes: 146
  pretrained: true
  model_name: yolov11s # yolo11n yolo11s yolo11m yolo11l yolo11x